feat: Use a tag instead of onClick in search result
It will allow the user to choose if he want current tab (default or
new tab)

Exception: navigating with keyboard and pressing Enter still use
onClick