fix(babel-preset-cozy-app): Publish validate.js file
Since this file is imported by `index.js` but not published, we get the
following error when we use it in apps:

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module './validate'
```