feat: Update @babel/runtime to 7.18.6
After this change #1631, commands like
`yarn start` or `yarn build` on some libs
were causing this error
```
Error: [BABEL]: Cannot find module '@babel/plugin-syntax-jsx'
```
I haven't found out exactly which version fixes this,
but the problem is no longer on version `7.18.6`.