fix: Don't import Q from cozy-client
Sometimes when running tests we simulate
a JSDom env so we use the browser entry
point from the package.json

But we can have few issues with circular
deps.

The case:
Tests on Cozy-client
Cozy-client has jas configured for browser
Cozy-Client import cozy-flags
Cozy-Flags imported Cozy-Client (from browser
entry point)
Cozy-client throwed an error:
TypeError: (0 , _cozyFlags.default) is not a function

Common issue when working with node / browser env.

So let's not import all files from cozy-client,
just the one needed.